root: true

env:
  browser: true,
  mocha: true

extends:
  - xo-react/space
  - xo-space/esnext

parser: babel-eslint

rules:
  curly:
    - error
    - multi-or-nest
    - consistent
  keyword-spacing:
    - error
    - overrides:
        if:
          after: false
  no-return-assign: off
  object-curly-spacing:
    - error
    - always
  react/jsx-handler-names:
    - error
    - eventHandlerPrefix: on
